### ISSUE TITLE
FreeBSD images need to be updated

### ISSUE THREAD

**Issue by dridi** [espebra/vagrant-skel#8]
Trying to install anything leads ineluctably to this: https://forums.freebsd.org/threads/59313/

**Comment by dridi** [comment]
In the meantime I'm using the official `freebsd/FreeBSD-11.0-CURRENT` box but it automatically shuts down after 10 minutes. Ever heard of that by any chance while making your own boxes?

**Comment by espebra** [comment]
Posted to the wrong repository. This repository only contains the Vagrantfile while the boxes are located elsewhere.
